server:
  port: 8081
  servlet:
    context-path: /girl

girl:
  cupSize: B
  age: 18
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl?characterEncoding=utf-8
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true